from django.test import TestCase
from rest_framework.test import APIClient
from django.urls import reverse
from .models import Candidate, Committee, Contributor, Employer, Contribution, Party
from datetime import date

class CandidateContributorsTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        # Create a party
        self.party = Party.objects.create(id="DEM", name="Democratic Party")
        # Create a candidate
        self.candidate = Candidate.objects.create(
            CAND_ID="P00000001",
            CAND_NAME="Test Candidate",
            CAND_PTY_AFFILIATION=self.party,
            CAND_ELECTION_YR=2024,
            CAND_OFFICE="P"
        )
        # Create a committee for the candidate
        self.committee = Committee.objects.create(
            CMTE_ID="C00000001",
            CMTE_NM="Test Committee",
            CAND_ID=self.candidate
        )
        # Create an employer
        self.employer = Employer.objects.create(name="Test Employer")
        # Create a contributor with that employer
        self.contributor = Contributor.objects.create(
            full_name="Test Contributor",
            zip_code="12345",
            employer=self.employer
        )
        # Create a contribution from that contributor to that committee
        self.contribution = Contribution.objects.create(
            contributor=self.contributor,
            committee=self.committee,
            amount=100.00,
            receipt_date=date(2024, 1, 1)
        )

    def test_top_contributors_action(self):
        # The URL name is generated by DRF as {basename}-{action_name}
        url = reverse('candidates-top-contributors', kwargs={'pk': self.candidate.CAND_ID})
        response = self.client.get(url)
        
        self.assertEqual(response.status_code, 200)
        data = response.data
        
        self.assertIn('top_individuals', data)
        self.assertIn('top_employers', data)
        
        # Verify individuals
        self.assertEqual(len(data['top_individuals']), 1)
        self.assertEqual(data['top_individuals'][0]['name'], "Test Contributor")
        self.assertEqual(data['top_individuals'][0]['total'], 100.0)
        self.assertEqual(data['top_individuals'][0]['employer_name'], "Test Employer")
        
        # Verify employers
        self.assertEqual(len(data['top_employers']), 1)
        self.assertEqual(data['top_employers'][0]['name'], "Test Employer")
        self.assertEqual(data['top_employers'][0]['total'], 100.0)

    def test_top_contributors_aggregation(self):
        # Add another contribution from the same person
        Contribution.objects.create(
            contributor=self.contributor,
            committee=self.committee,
            amount=50.00,
            receipt_date=date(2024, 1, 2)
        )
        
        url = reverse('candidates-top-contributors', kwargs={'pk': self.candidate.CAND_ID})
        response = self.client.get(url)
        
        self.assertEqual(response.status_code, 200)
        data = response.data
        
        # Total should be 150.0
        self.assertEqual(data['top_individuals'][0]['total'], 150.0)
        self.assertEqual(data['top_employers'][0]['total'], 150.0)
