# Generated by Django 5.2.7 on 2025-11-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FECContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMTE_ID', models.CharField(help_text='9-character alpha-numeric code assigned to a committee by the FEC.', max_length=9, verbose_name='Filer identification number')),
                ('AMNDT_IND', models.CharField(blank=True, help_text='N = New, A = Amendment, T = Termination.', max_length=1, null=True, verbose_name='Amendment indicator')),
                ('RPT_TP', models.CharField(blank=True, help_text='Type of report filed (e.g., 12G).', max_length=3, null=True, verbose_name='Report type')),
                ('TRANSACTION_PGI', models.CharField(blank=True, help_text='Election for which contribution was made (e.g., P2018).', max_length=5, null=True, verbose_name='Primary-general indicator')),
                ('IMAGE_NUM', models.CharField(blank=True, help_text='11- or 18-digit FEC image number.', max_length=18, null=True, verbose_name='Image number')),
                ('TRANSACTION_TP', models.CharField(blank=True, help_text='Transaction type code (e.g., 30T, 31E, etc.).', max_length=4, null=True, verbose_name='Transaction type')),
                ('ENTITY_TP', models.CharField(blank=True, help_text='CAN, CCM, COM, IND, ORG, PAC, PTY.', max_length=3, null=True, verbose_name='Entity type')),
                ('NAME', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contributor name')),
                ('CITY', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('STATE', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('ZIP_CODE', models.CharField(blank=True, max_length=9, null=True, verbose_name='ZIP code')),
                ('EMPLOYER', models.CharField(blank=True, max_length=38, null=True, verbose_name='Employer')),
                ('OCCUPATION', models.CharField(blank=True, max_length=38, null=True, verbose_name='Occupation')),
                ('TRANSACTION_DT', models.DateField(blank=True, null=True, verbose_name='Transaction date')),
                ('TRANSACTION_AMT', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Transaction amount')),
                ('OTHER_ID', models.CharField(blank=True, help_text='Contributor’s FEC ID (if committee or candidate).', max_length=9, null=True, verbose_name='Other ID')),
                ('TRAN_ID', models.CharField(blank=True, help_text='Unique ID for each transaction in a report.', max_length=32, null=True, verbose_name='Transaction ID')),
                ('FILE_NUM', models.BigIntegerField(blank=True, null=True, verbose_name='File number / Report ID')),
                ('MEMO_CD', models.CharField(blank=True, help_text="'X' indicates memo item (not part of total).", max_length=1, null=True, verbose_name='Memo code')),
                ('MEMO_TEXT', models.CharField(blank=True, max_length=100, null=True, verbose_name='Memo text')),
                ('SUB_ID', models.BigIntegerField(help_text='Unique row ID (required).', unique=True, verbose_name='FEC record number')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-TRANSACTION_DT'],
                'indexes': [models.Index(fields=['CMTE_ID'], name='api_feccont_CMTE_ID_aa1cda_idx'), models.Index(fields=['NAME'], name='api_feccont_NAME_99113d_idx'), models.Index(fields=['TRANSACTION_DT'], name='api_feccont_TRANSAC_5edcbe_idx'), models.Index(fields=['TRANSACTION_AMT'], name='api_feccont_TRANSAC_c702e2_idx')],
            },
        ),
    ]
