# Generated by Django 5.2.7 on 2025-11-10 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feccontribution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feccontribution',
            options={'ordering': ['-TRANSACTION_DT'], 'verbose_name': 'FEC Contribution', 'verbose_name_plural': 'FEC Contributions'},
        ),
    ]
