# Generated by Django 5.2.7 on 2025-11-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_feccontribution_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feccontribution',
            name='id',
        ),
        migrations.AlterField(
            model_name='feccontribution',
            name='CMTE_ID',
            field=models.CharField(help_text='9-character alpha-numeric code assigned to a committee by the FEC.', max_length=9, primary_key=True, serialize=False, verbose_name='Filer identification number'),
        ),
    ]
