# Generated by Django 5.2.7 on 2025-11-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_feccontribution_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feccontribution',
            name='CMTE_ID',
            field=models.CharField(help_text='9-character alpha-numeric code assigned to a committee by the FEC.', max_length=9, verbose_name='Filer identification number'),
        ),
        migrations.AlterField(
            model_name='feccontribution',
            name='SUB_ID',
            field=models.BigIntegerField(help_text='Unique row ID (required).', primary_key=True, serialize=False, unique=True, verbose_name='FEC record number'),
        ),
    ]
