# Generated by Django 5.2.7 on 2025-11-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_feccontribution_cmte_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMTE_ID', models.CharField(help_text='9-character ID assigned by the FEC.', max_length=9, unique=True, verbose_name='Committee ID')),
                ('CMTE_NM', models.CharField(blank=True, max_length=200, null=True, verbose_name='Committee Name')),
                ('TRES_NM', models.CharField(blank=True, help_text='Officially registered treasurer for the committee.', max_length=90, null=True, verbose_name="Treasurer's Name")),
                ('CMTE_ST1', models.CharField(blank=True, max_length=34, null=True, verbose_name='Street 1')),
                ('CMTE_ST2', models.CharField(blank=True, max_length=34, null=True, verbose_name='Street 2')),
                ('CMTE_CITY', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('CMTE_ST', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('CMTE_ZIP', models.CharField(blank=True, max_length=9, null=True, verbose_name='ZIP Code')),
                ('CMTE_DSGN', models.CharField(blank=True, help_text='A=Authorized, B=Lobbyist, D=Leadership, J=Joint, P=Principal, U=Unauthorized', max_length=1, null=True, verbose_name='Committee Designation')),
                ('CMTE_TP', models.CharField(blank=True, help_text='Single-character committee type code.', max_length=1, null=True, verbose_name='Committee Type')),
                ('CMTE_PTY_AFFILIATION', models.CharField(blank=True, max_length=3, null=True, verbose_name='Party Affiliation')),
                ('CMTE_FILING_FREQ', models.CharField(blank=True, help_text='A=Admin terminated, D=Debt, M=Monthly, Q=Quarterly, T=Terminated, W=Waived', max_length=1, null=True, verbose_name='Filing Frequency')),
                ('ORG_TP', models.CharField(blank=True, help_text='C=Corporation, L=Labor, M=Membership, T=Trade, V=Cooperative, W=Corp w/o capital stock', max_length=1, null=True, verbose_name='Interest Group Category')),
                ('CONNECTED_ORG_NM', models.CharField(blank=True, max_length=200, null=True, verbose_name='Connected Organization Name')),
                ('CAND_ID', models.CharField(blank=True, help_text='Candidate ID (if applicable)', max_length=9, null=True, verbose_name='Candidate ID')),
            ],
            options={
                'verbose_name': 'FEC Committee',
                'verbose_name_plural': 'FEC Committees',
                'db_table': 'api_committee',
            },
        ),
    ]
